# config.yaml
root_dir: null
valid_filepath: null
train_filepath: null
test_filepath: null
checkpoint_path: null
mode: train # train or eval

train:
  learning_rate: 0.0001
  num_epochs: 20
  batch_size: 8
  class_weights: [1, 1]
  ignore_index: -1
  weight_decay: 0.1

model:
  freeze_backbone: False
  num_classes: 2

dataloader:
  # 3*(Blue, Green, Red, Narrow NIR, SWIR 1, SWIR 2)
  bands: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17]
  mean:
    [
      23096.630859375,
      35603.5,
      37794.5390625,
      32105.447265625,
      44332.25390625,
      47126.90234375,
    ]
  std:
    [
      55801.23828125,
      54464.671875,
      43618.5,
      28412.44140625,
      33833.23046875,
      41449.89453125,
    ]
  img_size: 224
  temporal_dim: 3
  replace_label: [-9999, -1]
  reduce_to_zero: False
  no_data_value: -9999
  constant_multiplier: 1.0

test:
  img_size: 224
  crop_size: 224
  stride: 224
  mask_cloud: False
